chore: test solution
matter-labs/tutorials pull request #6
Opened 2023-08-25 13:51 UTC by abilevych

# What :computer:

- created an infrastructure for tests
- optimized the test code related to Hello World scenario
- integrated the CI/CD test execution per commit with the era-test-node

# Why :hand:

- integration test checks per PR

2023-08-26 15:54 UTC, idea404 requested changes
Some remarks, a good starting point

2023-08-26 15:54 UTC, idea404 commented on yarn.lock
> -"@achrinza/node-ipc@9.2.2":
How come the lockfile changed if there are no changes in the package.json deps?

2023-08-26 15:54 UTC, idea404 commented on hello-world/test/main.test.ts
>  });
I'd try adding some failing tests too, like passing wrong param types for example. Important to demonstrate that testing also involves testing unexpected scenarios

2023-08-29 13:42 UTC, idea404 requested changes
Some minor suggestions

2023-08-29 13:42 UTC, idea404 commented on tests/README.md
> +To have a possibility of test execution there needs to install a local node (L2) based on the next repository https://github.com/matter-labs/era-test-node.
```suggestion
To execute tests, you need to install a local node (L2) from the following repository: https://github.com/matter-labs/era-test-node
```

2023-08-29 13:42 UTC, idea404 commented on tests/README.md
> +This document contains an instruction of the test infrastructure preparation/running tests locally.
```suggestion
This document provides instructions for preparing the test infrastructure and running tests locally.
```

2023-08-29 13:57 UTC, idea404 approved these changes

2023-08-29 13:57 UTC, merged

2024-01-13 11:39 UTC, AMER88795 commented on tests/README.md
> +To have a possibility of test execution there needs to install a local node (L2) based on the next repository https://github.com/matter-labs/era-test-node.
Yas[]()[]()https://zerion.io/premium

2024-01-13 11:40 UTC, AMER88795 commented on tests/README.md
> +This document contains an instruction of the test infrastructure preparation/running tests locally.
![googleads_mobile_ios_swift_adaptive_banner_example.zip](https://github.com/matter-labs/tutorials/files/13927812/googleads_mobile_ios_swift_adaptive_banner_example.zip)

2024-01-13 11:41 UTC, AMER88795 commented on tests/README.md
> +To have a possibility of test execution there needs to install a local node (L2) based on the next repository https://github.com/matter-labs/era-test-node.
@![Screenshot 2024-01-05 at 11.29.17.png](https://github.com/matter-labs/tutorials/assets/150193026/9ef6889b-beb4-4d62-badc-3507e63f70fc)